### ISSUE TITLE
Damn Straight Overflow

### ISSUE THREAD

**Issue by DarkJDL** [Celicath/PokerPlayerMod#4]
Hello it's me again, I still like your mod but I found another (not crashing, yet)  problem

I've made a  "Damn Straight+" Build And I got to numbers where my Clubs deal Negative damage or give Negative Block (from club shade)

Here are 3 screenshots, one with less Damn Straight and one with 2 more where the Clubs damage fix itself but that time it's the block broke. (I uploaded them using GitHub's attach files, I don't know if that works well it's my first time)

potential quick fix solution would be to add a maximum to the % of Damn Straight,  it did not break for quite a while so I'd think something like 500000% would be enough (as if there's anything that can survive that anyways)

A more reasonable fix would be to make DamnStraight  give +200% and not double. doubling scales up REALLY quick

Have a nice day! :)

![PokerMod DamnStraight3](https://user-images.githubusercontent.com/35188950/182955828-f6a84cd6-ad69-41e9-a915-c6ba42396c6f.png)
![PokerMod DamnStraight2](https://user-images.githubusercontent.com/35188950/182955833-1aa53e7f-a311-41c0-9271-cb8079040d6a.png)
![PokerMod DamnStraight](https://user-images.githubusercontent.com/35188950/182955834-143d2666-3437-483e-a532-078bd223b284.png)
.

**Comment by Celicath** [comment]
Hi, thanks (again) for playing this mod.

I agree that changing Damn Straight to give +200% instead of doubling will make it more balanced and reasonable. However, I don't want to do that because the doubling makes Damn Straight feel unique from others, and it gives people a wow moment. Poker Player isn't really about balance or, uh, 'reasonableness'.

Interestingly, I thought about the integer overflow and wrote this tooltip:

![image](https://user-images.githubusercontent.com/1008668/183076041-9075de04-9408-4474-b2c4-ea2879d7f494.png)

This is shown after you play 24 Damn Straights. It doesn't help much because integer overflow happens much earlier. And I believe this isn't meaningful or funny to non-programmers.

There's an interface issue with high numbers as well. In the Showdown Power calculator, the numbers written on each suit overlap and become messy.

So my solution will be, set the maxmimum value for how much heal/block/damage each suit can during showdown. I need to make sure integer overflow never occurs as well. The cap will be something like 999 or 9999, which I need to experiment a little to figure out.

**Comment by Celicath** [comment]
Well, making a cap wasn't easy due to how symbols are generated(I need to calculate how much damage each flying symbol does), so I made a cap on Damn Straight power instead. No more than 16 Damn Straights should be enough to prevent overflow.

This fix should be in 1.0.9.
